name: Deploy Test

on:
  push:
    branches:
      - 'main'
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name, (include initial v)'
        required: true
        type: string

env:
  TAG_NAME: ${{ inputs.tag }}
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # upload to release contents

    steps:
      - name: Set version on release
        if: github.event_name == 'release'
        run: |
          echo "TAG_NAME=${GITHUB_REF##*/}" >> "$GITHUB_ENV"

      - if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: "${{ env.TAG_NAME }}"

      - if: github.event_name == 'release' || github.event_name == 'push'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - run: echo "$TAG_NAME"

      - name: Write version into pom if overridden
        if: github.event_name == 'workflow_dispatch' ||  github.event_name == 'release'
        run: sed -i "s|<version>.*-SNAPSHOT</version>|<version>${TAG_NAME##v}</version>|" sample_file.txt

      - run: cat sample_file.txt

      - name: Attach artifacts to release
        if: github.event_name == 'workflow_dispatch' ||  github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for f in $(find . -name sample_file.txt); do
            gh release upload ${{ env.TAG_NAME }} $f
          done
