name: Publish to LuaRocks

on: 
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v9

      - uses: leafo/gh-actions-luarocks@v4

      - run: echo "upload rockspecs/du-mocks-${GITHUB_REF##*/v}-1.rockspec --api-key ${{ secrets.API_KEY }}"
