name: Publish to LuaRocks

on: 
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - uses: leafo/gh-actions-lua@8

      - uses: leafo/gh-actions-luarocks@8

      - run: echo "upload rockspecs/du-mocks-${GITHUB_REF##*/v}-1.rockspec --api-key ${{ secrets.API_KEY }}"
